package ridl.conformance

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import ridl.codegen.kotlin.Wire
import java.nio.file.Path
import kotlin.io.path.appendText
import kotlin.io.path.writeText

/**
 * The generated-file marker and the project header (driftsys/ridl#746): the
 * pinned `ridl` puts both in the request, and every file the plugin writes
 * through it starts with them, as every in-tree backend's file does.
 */
class PreambleTest {
    @TempDir
    lateinit var work: Path

    private val marker = "@generated by ridl from package veh.cabin. Do not edit."

    private fun kotlinFiles(out: Path): Map<String, String> =
        Harness.files(out).filterKeys { it.endsWith(".kt") }.mapValues { it.value.decodeToString() }

    @Test
    fun `the request carries the marker and no header by default`() {
        val request = Wire.readRequest(Harness.capturedRequest("cabin", work))
        assertEquals(marker, request.generatedMarker)
        assertEquals("", request.header)
    }

    @Test
    fun `every file starts with the marker`() {
        val out = Harness.build(Harness.copyOf("cabin", work), work.resolve("out"), "--plugin", "kotlin=${Harness.plugin}")
        val files = kotlinFiles(out)
        assertEquals(3, files.size, files.keys.toString())
        for ((path, text) in files) {
            assertTrue(text.startsWith("// $marker\n\n"), "$path starts:\n${text.take(200)}")
        }
    }

    @Test
    fun `every file starts with the marker, then the project header`() {
        val pkg = Harness.copyOf("cabin", work)
        pkg.resolve("HEADER.txt").writeText("Copyright 2026 Example  \r\n\r\nSPDX-License-Identifier: MIT\n\n")
        pkg.resolve("ridl.toml").appendText("\n[codegen]\nheader-file = \"HEADER.txt\"\n")
        val out = Harness.build(pkg, work.resolve("out"), "--plugin", "kotlin=${Harness.plugin}")
        val files = kotlinFiles(out)
        assertEquals(3, files.size, files.keys.toString())
        val expected = "// $marker\n// Copyright 2026 Example\n//\n// SPDX-License-Identifier: MIT\n\n"
        for ((path, text) in files) {
            assertTrue(text.startsWith(expected), "$path starts:\n${text.take(300)}")
        }
    }
}
