set shell := ["bash", "-euo", "pipefail", "-c"]

fmt:
    prim fmt .

fmt-check:
    prim fmt --check .

check:
    prim lint .
    scripts/check-repo.sh
    ./gradlew check

test:
    ./gradlew test

build: fmt-check check install-check
    ./gradlew assemble

# The runtime sources as an Android tree vendors them, with an Android.bp
# (packaging/android/README.md): build/vendor/ridl-rt-kt-<version>-android.tar.gz.
vendor-package:
    python3 scripts/vendor-package.py

# install.sh end to end against a fixture release on the local disk: a fake
# distribution and its SHA256SUMS, then a second install over the first, then
# a tarball whose checksum does not match, which must be refused.
install-check:
    #!/usr/bin/env bash
    set -euo pipefail
    scratch="$(mktemp -d)"
    trap 'rm -rf "$scratch"' EXIT
    version="v0.0.0-install-check"
    url="$(RIDLC_GEN_KOTLIN_VERSION="$version" RIDLC_GEN_KOTLIN_DRY_RUN=1 bash install.sh)"
    expected="https://github.com/driftsys/ridlc-gen-kotlin/releases/download/$version/ridlc-gen-kotlin-0.0.0-install-check.tar"
    [ "$url" = "$expected" ] || { echo "install-check: dry run printed $url, expected $expected" >&2; exit 1; }
    tarball="$(basename "$url")"
    reldir="$scratch/release/$version"
    root="$scratch/dist/ridlc-gen-kotlin-0.0.0-install-check"
    mkdir -p "$reldir" "$root/bin" "$root/lib"
    printf '#!/bin/sh\necho ridlc-gen-kotlin install-check\n' > "$root/bin/ridlc-gen-kotlin"
    chmod +x "$root/bin/ridlc-gen-kotlin"
    : > "$root/lib/ridlc-gen-kotlin-all.jar"
    tar -cf "$reldir/$tarball" -C "$scratch/dist" "$(basename "$root")"
    if command -v sha256sum >/dev/null 2>&1; then sum=(sha256sum); else sum=(shasum -a 256); fi
    (cd "$reldir" && "${sum[@]}" "$tarball" > SHA256SUMS)
    run() {
      RIDLC_GEN_KOTLIN_VERSION="$version" RIDLC_GEN_KOTLIN_BASE_URL="file://$scratch/release" \
        RIDLC_GEN_KOTLIN_HOME="$scratch/home" RIDLC_GEN_KOTLIN_INSTALL_DIR="$scratch/bin" bash install.sh
    }
    run 2>/dev/null
    run 2>/dev/null
    [ "$("$scratch/bin/ridlc-gen-kotlin")" = "ridlc-gen-kotlin install-check" ] \
      || { echo "install-check: the installed link does not run the distribution" >&2; exit 1; }
    [ -f "$scratch/home/$version/lib/ridlc-gen-kotlin-all.jar" ] \
      || { echo "install-check: lib/ was not installed" >&2; exit 1; }
    echo corrupt >> "$reldir/$tarball"
    if run 2>/dev/null; then echo "install-check: a tarball with a wrong checksum was installed" >&2; exit 1; fi
    echo "install-check: install.sh verified"

# The JVM demo: the cabin package generated by the plugin, round-tripping
# over the loopback (samples/cabin).
demo:
    ./gradlew -q :samples:cabin:run

# The plugin distribution: bin/ridlc-gen-kotlin over lib/ridlc-gen-kotlin-all.jar.
dist:
    ./gradlew :ridlc-gen-kotlin:shadowDistZip :ridlc-gen-kotlin:shadowDistTar :ridlc-gen-kotlin:installShadowDist
    @echo "modules/ridlc-gen-kotlin/build/install/ridlc-gen-kotlin/bin/ridlc-gen-kotlin"

# The four JVM libraries into the local Maven repository, for a consumer
# outside this repository — the Binder runtime depends on ridl-rt-kt (§6), and
# runs ridl-rt-kt-conformance's suite over itself.
publish-local:
    ./gradlew publishToMavenLocal

# The four JVM libraries to GitHub Packages, at the version gradle.properties
# names. Needs the Gradle properties GitHubPackagesUsername and
# GitHubPackagesPassword, a token with write:packages; the ci workflow's snapshot
# job and the release workflow set them.
publish:
    ./gradlew publishAllPublicationsToGitHubPackagesRepository

# The conformance results as one release asset: the plugin's conformance tests
# against the pinned ridl release and the port contract suite over the
# loopback, packed by scripts/compliance-report.py into
# build/compliance/ridlc-gen-kotlin-<version>-compliance.tar.gz.
compliance:
    ./gradlew :conformance:test :ridl-rt-kt-conformance:test :ridl-rt-kt-loopback:test
    python3 scripts/compliance-report.py

# The Rust codec verdicts of the conformance module, regenerated from the
# pinned ridl release and compared with the committed files (#39); needs cargo,
# git and python3. `just rust-verdicts --write` writes them instead. The test
# run writes the corpus the Rust programs read; its own verdict is the jvm job's.
rust-verdicts *args:
    rm -f modules/conformance/build/spike/*.txt
    ./gradlew -q :conformance:installRidl
    -./gradlew -q :conformance:test --rerun --tests ridl.conformance.CodecTest --tests ridl.conformance.SpikeTest
    python3 scripts/rust-verdicts.py {{args}}

lint-commits base="main":
    @if git show-ref --verify --quiet "refs/remotes/origin/{{base}}"; then \
      base_ref="origin/{{base}}"; \
    elif git rev-parse --verify --quiet "{{base}}^{commit}" >/dev/null 2>&1; then \
      base_ref="{{base}}"; \
    else \
      printf 'Unable to resolve commit-lint base: %s or origin/%s\n' "{{base}}" "{{base}}" >&2; \
      exit 1; \
    fi; \
    git std lint --range "$base_ref..HEAD"

verify: lint-commits build

bootstrap:
    @missing=""; \
      for tool in git-std prim just java; do \
        if ! command -v "$tool" >/dev/null 2>&1; then missing="$missing $tool"; fi; \
      done; \
      if [ -n "$missing" ]; then \
        printf 'Missing required tools:%s\n' "$missing"; \
        exit 1; \
      fi; \
      if ! java -version 2>&1 | grep -Eq 'version "(1[7-9]|[2-9][0-9])'; then \
        printf 'JDK 17 or later is required\n'; \
        exit 1; \
      fi; \
      printf 'Required tools available: git-std prim just java\n'
