package ridl.codegen.kotlin

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/** The comment block a generated file starts with: ridl's `comment_preamble` over `//`. */
class PreambleTest {
    private val marker = "@generated by ridl from package veh.cabin. Do not edit."

    @Test
    fun `no marker and no header is no preamble`() {
        assertEquals("", preamble("", ""))
    }

    @Test
    fun `the marker alone is one comment line and a blank line`() {
        assertEquals("// $marker\n\n", preamble(marker, ""))
    }

    @Test
    fun `each header line follows the marker, an empty one as a bare comment`() {
        assertEquals(
            "// $marker\n// Copyright 2026 Example\n//\n// SPDX-License-Identifier: MIT\n\n",
            preamble(marker, "Copyright 2026 Example\n\nSPDX-License-Identifier: MIT"),
        )
    }

    @Test
    fun `a header without a marker starts with a bare comment`() {
        assertEquals("//\n// Copyright 2026 Example\n\n", preamble("", "Copyright 2026 Example"))
    }
}
